services:
  bytebank-notification:
    build:
      context: .
    container_name: bytebank-notification
    environment:
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      SPRING_RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: bytebank
      RABBITMQ_PASS: bytebank123
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      WAHA_BASE_URL: http://host.docker.internal:3000
    ports:
      - "8084:8084"
    networks:
      - bytebank-net

networks:
  bytebank-net:
    external: true