services:
  bytebank-notification:
    build:
      context: ../
    container_name: bytebank-notification
    environment:
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      SPRING_RABBITMQ_HOST: rabbitmq
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    ports:
      - "8084:8084"
    networks:
      - bytebank-net

networks:
  bytebank-net:
    external: true